### ISSUE TITLE
Беглый обзор, как и было запрошено

### ISSUE THREAD

**Issue by markiz** [JelF/can_camel#2]
Общее:
1. Почему postgres-only? 
2. Почему создаются миграции с номерами 00000000000001 и 00000000000002? Почему их вообще две? Почему одна из миграций [требует](https://github.com/JelF/can_camel/blob/master/lib/generators/can_camel/db/migrate/00000000000002_hstore_to_json.rb#L6) стандартного ввода и вообще что-то хочет от пользователя, который ни сном, ни духом о том, что же он устанавливает?
3. [Так константами пользоваться нельзя](https://github.com/JelF/can_camel/blob/master/lib/generators/can_camel/config/initializers/can_camel.rb#L3), используй классовые методы
4. Сегодня автолоадом пользоваться не рекомендуется, вместо этого просто сделай require всех нужных файлов
5. Я совершенно не понял, зачем сложности с хранением дерева целиком. Вначале можно предположить, что это для частичных матчей типа `can?(:admin, :write)`, но судя по всему только GroupNode третьего уровня вообще хранятся. Система получилась такая сложная, что ей требуется собственный линтер.
6. Не нашел где происходит создание нод

Стилистическое:
1. [reduce(true)](https://github.com/JelF/can_camel/blob/master/lib/can_camel/linter.rb#L16) на одном-двух аргументах не имеет смысла. То же самое, написанное руками через && намного легче понять. По правде говоря, я бы вообще на любом заранее известном наборе предикатов всё руками записал.
2. [Из названия спеки непонятно, что же там проверяется](https://github.com/JelF/can_camel/blob/master/spec/can_camel/validators/path_validators_spec.rb#L15). Попробую пояснить на аналогии: в калькуляторе деление на ноль вызывает ошибку. Нормальная спека звучит так: "деление на ноль вызывает ошибку". Спека курильщика: "вызывает ошибку".
3. [Исключения у тебя используются для control flow](https://github.com/JelF/can_camel/blob/master/lib/can_camel/linter.rb#L26). Это в принципе не очень страшно, но зачем?

**Comment by JelF** [comment]
>1. Почему postgres-only? 
hstore
>2. Почему создаются миграции с номерами 00000000000001 и 00000000000002? Почему их вообще две? Почему одна из миграций требует стандартного ввода и вообще что-то хочет от пользователя, который ни сном, ни духом о том, что же он устанавливает?
вторая миграция это заплатка #1 . Есть какие то инструменты для нормальной вставки таблиц?
>3. Так константами пользоваться нельзя, используй классовые методы
Это принципиальная проблема? Переделать не сложно, но хотелось бы знать о причинах хотя бы для того, чтобы их избегать
>4. Сегодня автолоадом пользоваться не рекомендуется, вместо этого просто сделай require всех нужных файлов
Мне нужен ленивый require вроде как
>5. Я совершенно не понял, зачем сложности с хранением дерева целиком. Вначале можно предположить, что это для частичных матчей типа can?(:admin, :write), но судя по всему только GroupNode третьего уровня вообще хранятся. Система получилась такая сложная, что ей требуется собственный линтер.
Наследование. Мой опыт работы с такими сложными таблицами прав, что для них нужна полновесная либа говорит о его крайней полезности. Как минимум выдача прав доступа на субьект или действие
>6. Не нашел где происходит создание нод
пока только ручное

>2. Из названия спеки непонятно, что же там проверяется. Попробую пояснить на аналогии: в калькуляторе деление на ноль вызывает ошибку. Нормальная спека звучит так: "деление на ноль вызывает ошибку". Спека курильщика: "вызывает ошибку".
там же складываются контексты, но мысль понял
>3. Исключения у тебя используются для control flow. Это в принципе не очень страшно, но зачем?
validate! семантически их бросает, мне так удобнее

**Comment by markiz** [comment]
> hstore

Зачем? Почему недостаточно просто сериализованного поля? Ну если все-таки обязательно, то надо где-то в ридми это прописать и желательно еще и проверять в рантайме.

> вторая миграция это заплатка #1 . Есть какие то инструменты для нормальной вставки таблиц?

Увы, не в курсе.
http://apidock.com/rails/Rails/Generator/Commands/Create/migration_template вот этот метод вроде для генерации миграций.

А про твой #1 я просто не понял, в чем собственно дело.

> Это принципиальная проблема? Переделать не сложно, но хотелось бы знать о причинах хотя бы для того, чтобы их избегать

Семантическая. Ну и при повторном присвоении константы интерпретатор ругнется в stderr.

> лол, я кажется просрал кусок фич :0

Вероятно, тебе придется как-то помечать "конечные" ноды. Потому что из `can!(:admin, :write)` следует `can?(:admin, :write)` и  `can?(:admin, :write, :poem)`, а из `can!(:user, :write, :poem)` не следует ни `can?(:user, :write, :prose)`, ни `can?(:user, :write)`.

**Comment by JelF** [comment]
>А про твой #1 я просто не понял, в чем собственно дело.
миграция с 0.1.0 до 0.2.0 убивает все данные
>Зачем? Почему недостаточно просто сериализованного поля? Ну если все-таки обязательно, то надо где-то в ридми это прописать и желательно еще и проверять в рантайме.
ну вообще говоря закладывается теоретическая возможность делать запросы по элементам этого hstore

**Comment by markiz** [comment]
Делай двойной отступ между блоком цитирования и ответа, чтобы не сливалось в кашу.

> миграция с 0.1.0 до 0.2.0 убивает все данные

Ну не убивай. Переименуй старую колонку, добавь новую, пройдись по всем элементам и обнови как надо, убери старую колонку. Пока у тебя меньше нескольких сотен тысяч элементов в таблице, `#find_each` + `#update_attributes` почти не занимают времени.

**Comment by JelF** [comment]
в версии 0.3.0 закрыты пункты
О: 1, 2, 5, 6

Остальные пункты будут пофикшены позднее
